divvy/authentication/routes.py
import re
from flask import Blueprint, render_template, request, redirect, url_for, flash
from divvy.forms import UserLoginForm
from divvy.models import User, db, check_password_hash
from flask_login import login_user, logout_user, current_user, login_required

auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    form = UserLoginForm()
    try:
        if request.method == "POST" and form.validate_on_submit():
            username = form.username.data
            email = form.email.data
            password = form.password.data
            print(email, username, password)

            user = User(email, username, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f"You have successfully crewated a user account {username}", 'user-created')

            return redirect(url_for('auth.signin'))

    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
    return render_template('signup.html', form = form)


@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    form = UserLoginForm()

    try:
        if request.method == "POST" and form.validate_on_submit():
            username = form.username.data
            email = form.email.data
            password = form.password.data
            print(email, username, password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were succesfully logged in via Email/Password', 'auth-success')
                return redirect(url_for('site.profile'))
            else:
                flash('Your Email/Password is incorrect.', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception("Invalid Form Data or User Does Not Exist, Please Check Your Form or Sign Up")
    return render_template('signin.html', form = form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('site.home'))

divvy/site/routes.py
from flask import Flask, Blueprint, request, render_template
import psycopg2

site = Blueprint('site', __name__, template_folder = 'site_templates')
try:
    conn = psycopg2.connect(database="Divvy", user="postgres", password="Dshm1234", host="localhost")
    print("connected")
except:
    print("I am unable to connect to the database")
mycursor = conn.cursor()
app = Flask(__name__)

@site.route('/')
def home():
    return render_template('home.html')
    
@site.route('/profile')
def profile(): 
    return render_template('profile.html')

@site.route('/trip')
def trip():
    mycursor.execute("SELECT * FROM trip")
    data = mycursor.fetchall()
    return render_template('trip.html', data=data)

@site.route('/index')
def index():
    return render_template('index.html')

divvy/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>{{ title }}}</title>
</head>
<body>
    <div class="container">
        <h1>{{ title }}</h1>
        <hr>
        {% block contntent %}{% endblock %}
    </div>
    {% block scripts %}{% endblock %}
    <nav class="ct-nav bg-danger">
        <div>
            <img src="../static/Images/icon-1.png" alt="">
        </div>
    
    
    <div>
        <ul id="horizontal-list">
            <a href="{{ url_for('site.home') }}">
                <li class="text-warning">Divvy Tracker</li>
            </a>
            <a href="{{ url_for('site.profile') }}">
                <li class="text-warning">Profile</li>
            </a>
            <a href="{{ url_for('auth.logout') }}">
                <li class="text-warning">Log Out</li>
            </a>
            <a href="{{ url_for('auth.signin') }}">
                <li class="text-warning">Sign-In</li>
            </a>
            <a href="{{ url_for('auth.signup') }}">
                <li class="text-warning">Sign-Up</li>
            </a>
            <a href="{{ url_for('site.trip') }}">
                <li class="text-warning">Table</li>
            </a>
            <a href="{{ url_for('site.index') }}">
                <li class="text-warning">index</li>
            </a>
        </ul>
    </div>
    </nav>
    {% block content %}

    {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>

divvy/templates/forms.html
<form method = "POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Enter email here...") }}
        </fieldset>
        <fieldset id="username-field">
            {{ form.username.label }}
            {{ form.username(class = "form-control", placeholder = "Enter username here...") }}
        </fieldset>
        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Enter password here...") }}
        </fieldset>

        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>
</form>